# Generated by Django 2.0.7 on 2018-08-01 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_archived',
        ),
    ]
