# Generated by Django 2.0.7 on 2018-07-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20180720_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='old_value',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
