# Generated by Django 2.0.7 on 2018-07-20 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='date_archived',
        ),
        migrations.RemoveField(
            model_name='boardmember',
            name='date_archived',
        ),
        migrations.RemoveField(
            model_name='card',
            name='date_archived',
        ),
        migrations.RemoveField(
            model_name='cardcomment',
            name='date_archived',
        ),
        migrations.RemoveField(
            model_name='cardmember',
            name='date_archived',
        ),
        migrations.RemoveField(
            model_name='column',
            name='date_archived',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='date_archived',
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='boards.Board'),
        ),
    ]
